name: Build & Publish docker

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: docker-build-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Cosign
        if: github.event_name == 'push'
        uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log into registry
        if: github.event_name == 'push'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Read version
        id: version
        run: (echo -n version=; cat VERSION) >> "$GITHUB_OUTPUT"
        
      - name: Generate tags & labels
        id: metadata
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: docker.io/firelightflagbot/cdk8s-python-uv          
          tags:
            type=raw,value=${{ steps.version.outputs.version }}
      
      - name: Build & Push Docker
        id: build-and-push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          provenance: mode=max
          sbom: true
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Sign the published docker image
        if: github.event_name == 'push'
        run: printenv TAGS | xargs -I {} cosign sign --yes {}@${DIGEST}
        env:
          TAGS: ${{ steps.metadata.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}


